export const GO_NEXT_STEP = 'ROOT:GO_NEXT_STEP';
export const GO_PREV_STEP = 'ROOT:GO_PREV_STEP';

export const SET_FACULTIES_LIST = 'ROOT::SET_FACULTIES_LIST';
export const SET_COURSES_LIST = 'ROOT::SET_COURSES_LIST';
export const SET_SUBJECTS_LIST = 'ROOT::SET_SUBJECTS_LIST';
export const SET_TESTS_LIST = 'ROOT::SET_TESTS_LIST';

export const SET_SELECTED_FACULTY = 'ROOT::SET_SELECTED_FACULTY';
export const SET_SELECTED_COURSE = 'ROOT::SET_SELECTED_COURSE';
export const SET_SELECTED_SUBJECT = 'ROOT::SET_SELECTED_SUBJECT';
export const SET_SELECTED_TEST = 'ROOT::SET_SELECTED_TEST';
